// @ts-check

/**
 * Sidebar configuration for the Knowledge Base.
 * Uses autogenerated items so docs are auto-discovered from subdirectories.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'SDET Skills',
      items: [
        {type: 'autogenerated', dirName: 'sdet-skills'},
        {type: 'ref', id: 'role-guides/sdet/python-for-sdet', label: 'Python for SDET (Role Guide)'},
        {type: 'ref', id: 'role-guides/sdet/advanced-python-for-sdet', label: 'Advanced Python for SDET (Role Guide)'},
      ],
      link: {type: 'generated-index', description: 'Test automation, quality engineering, and SDET practices.'},
    },
    {
      type: 'category',
      label: 'SRE Skills',
      items: [
        {type: 'autogenerated', dirName: 'sre-skills'},
        {type: 'ref', id: 'role-guides/sre/python-for-sre', label: 'Python for SRE (Role Guide)'},
        {type: 'ref', id: 'role-guides/sre/advanced-python-for-sre', label: 'Advanced Python for SRE (Role Guide)'},
      ],
      link: {type: 'generated-index', description: 'Site reliability engineering: observability, incident response, and reliability practices.'},
    },
    {
      type: 'category',
      label: 'SDE Skills',
      items: [
        {type: 'autogenerated', dirName: 'sde-skills'},
        {type: 'ref', id: 'role-guides/sde/python-for-sde', label: 'Python for SDE (Role Guide)'},
        {type: 'ref', id: 'role-guides/sde/advanced-python-for-sde', label: 'Advanced Python for SDE (Role Guide)'},
      ],
      link: {type: 'generated-index', description: 'Software development engineering topics and patterns.'},
    },
    {
      type: 'category',
      label: 'AI Skills',
      items: [{type: 'autogenerated', dirName: 'ai-skills'}],
      link: {type: 'generated-index', description: 'AI-assisted engineering tools and workflows.'},
    },
    {
      type: 'category',
      label: 'Fundamentals',
      items: [{type: 'autogenerated', dirName: 'fundamentals'}],
      link: {type: 'generated-index', slug: '/fundamentals', description: 'Language fundamentals and coding best practices, from basic to advanced.'},
    },
    {
      type: 'category',
      label: 'Role Guides',
      items: [{type: 'autogenerated', dirName: 'role-guides'}],
      link: {type: 'generated-index', slug: '/role-guides', description: 'How the fundamentals apply to each role: SDET, SRE, and SDE.'},
    },
    {
      type: 'category',
      label: 'Learning Path',
      items: [{type: 'autogenerated', dirName: 'learning-path'}],
      link: {type: 'generated-index', slug: '/learning-path', description: 'An ordered learning path: roadmap, syllabus, comprehensive guide, and mini-projects.'},
    },
  ],
};

export default sidebars;
