// @ts-check

/**
 * Sidebar configuration for the Knowledge Base.
 * Uses autogenerated items so docs are auto-discovered from subdirectories.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'SDET Skills',
      items: [{type: 'autogenerated', dirName: 'sdet-skills'}],
      link: {type: 'generated-index', description: 'Test automation, quality engineering, and SDET practices.'},
    },
    {
      type: 'category',
      label: 'SRE Skills',
      items: [{type: 'autogenerated', dirName: 'sre-skills'}],
      link: {type: 'generated-index', description: 'Site reliability engineering: observability, incident response, and reliability practices.'},
    },
    {
      type: 'category',
      label: 'SDE Skills',
      items: [{type: 'autogenerated', dirName: 'sde-skills'}],
      link: {type: 'generated-index', description: 'Software development engineering topics and patterns.'},
    },
  ],
};

export default sidebars;
