// @ts-check

/**
 * Sidebar configuration for the Cheat Sheets section.
 * Flat, autogenerated from the /cheatsheets content directory — one
 * cheat sheet per topic, cross-linked with its full guide in /docs.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebarsCheatsheets = {
  cheatsheets: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebarsCheatsheets;
